version: '3'

services:
    influxdb:
        image: influxdb:latest
        ports:
            - '8086:8086'
        volumes:
            - influxdb-storage:/var/lib/influxdb
        environment:
            - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
            - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
    worker:
        restart: 'no'
        build:
            context: . 
            dockerfile: ./Dockerfile 
        environment:
            - API_ADDRESS=${API_ADDRESS}
        command: go run main.go
        volumes:
            - .:/code 
        depends_on:
            - influxdb

volumes:
    influxdb-storage: